name: Build images and push (on master branch or on schedule)

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image-tag: [22-bookworm, 22-trixie, 24-bookworm, 24-trixie, 26-trixie]
    steps:
    - uses: actions/checkout@master
    - name: Test
      run: |
        chmod +x runTests.sh && ./runTests.sh ${{ matrix.base-image-tag }}
    - name: Build
      run: |
        docker build --build-arg=BASE_IMAGE_TAG=${{ matrix.base-image-tag }} --tag ppiper/node-browsers:${{ matrix.base-image-tag }} .
    - name: Tag latest image
      if: ${{ matrix.base-image-tag == '26-trixie' }}
      run: |
        docker tag ppiper/node-browsers:${{ matrix.base-image-tag }} ppiper/node-browsers:latest
    - name: Push
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
        docker push ppiper/node-browsers:${{ matrix.base-image-tag }}
        if [ "${{ matrix.base-image-tag }}" == 26-trixie ]; then
          docker push ppiper/node-browsers:latest
        fi
