name: Build images and push (on master branch or on schedule)

on:
  push:
    branches:
      - "**"
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image: [10-buster, 12-buster, 14-buster]
    steps:
    - uses: actions/checkout@master
    - name: Test
      run: |
        chmod +x runTests.sh && ./runTests.sh ${{ matrix.base-image }}
    - name: Build
      run: |
        echo ${{ secrets.DH_PW }} | docker login -u ${{ secrets.DH_USER }} --password-stdin
        docker build --build-arg=BASE_IMAGE=node:${{ matrix.base-image }} --tag ppiper/node-browsers:${{ matrix.base-image }} .
        if [ "${{ matrix.base-image }}" == 10-buster ]; then
          docker tag ppiper/node-browsers:10-buster ppiper/node-browsers:latest
        fi
    - name: Push
      if: ${{ github.ref == 'ref/head/master' }}
      run: |
        docker push ppiper/node-browsers:${{ matrix.base-image }}
        if [ "${{ matrix.base-image }}" == 10-buster ]; then
          docker push ppiper/node-browsers:latest
        fi
