name: Build images and push (on master branch or on schedule)

on:
  push:
    branches:
      - "**"
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image-tag: [10-buster, 12-buster, 14-buster]
    steps:
    - uses: actions/checkout@master
    - name: Test
      run: |
        chmod +x runTests.sh && ./runTests.sh ${{ matrix.base-image-tag }}
    - name: Build
      run: |
        docker build --build-arg=BASE_IMAGE_TAG=${{ matrix.base-image-tag }} --tag ppiper/node-browsers:${{ matrix.base-image-tag }} .
        docker tag ppiper/node-browsers:${{ matrix.base-image-tag }} ghcr.io/sap/ppiper-node-browsers:${{ matrix.base-image-tag }}
    - name: Tag latest image
      if: ${{ matrix.base-image-tag == '10-buster' }}
      run: |
        docker tag ppiper/node-browsers:${{ matrix.base-image-tag }} ppiper/node-browsers:latest
        docker tag ghcr.io/sap/ppiper-node-browsers:${{ matrix.base-image-tag }} ghcr.io/sap/ppiper-node-browsers:latest
    - name: Push
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
        echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ secrets.CR_USER }} --password-stdin
        docker push ppiper/node-browsers:${{ matrix.base-image-tag }}
        docker push ghcr.io/sap/ppiper-node-browsers:${{ matrix.base-image-tag }}
        if [ "${{ matrix.base-image-tag }}" == 10-buster ]; then
          docker push ppiper/node-browsers:latest
          docker push ghcr.io/sap/ppiper-node-browsers:latest
        fi
