name: Build images and push (on master branch or on schedule)

on:
  push:
    branches:
      - "**"
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run CI
      run: |
        echo ${{ secrets.DH_PW }} | docker login -u ${{ secrets.DH_USER }} --password-stdin
        docker build -t ppiper/node-browsers:latest .
        docker build -t ppiper/node-browsers:node12 node12
        docker push ppiper/node-browsers:latest
        docker push ppiper/node-browsers:node12
